baseurl = "/"
languageCode = "en-gb"
title = "gingerBill"
theme = "gb-theme"
googleAnalytics = ""
disqusShortname = ""
preserveTaxonomyNames = true
# footnotereturnlinkcontents = "â†©"
disableHugoGeneratorInject = true

pygmentsCodeFences = false
pygmentsStyle = "manni"

staticDir = ["static"]

[permalinks]
    article = "/article/:year/:month/:day/:slug/"
    show = "/show/:slug/"

[taxonomies]
    category = "category"
    tag      = "tags"
    series   = "series"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Articles"
    url = "/article/"
    weight = 2
[[menu.main]]
    name = "Podcast"
    url = "/show/"
    weight = 3
[[menu.main]]
    name = "Odin"
    url = "/odin/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/article/index.xml"

[params]
    description = ""
    footer = "&copy; 2007&ndash;2020 Ginger Bill"



[markup.goldmark.renderer]
unsafe=true
